# Generated by Django 4.1.3 on 2022-12-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_student_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
