# Generated by Django 4.1.3 on 2022-12-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('authors', models.JSONField()),
            ],
        ),
    ]
