# Generated by Django 4.1.3 on 2022-12-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_delete_student_remove_games_authors_games_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='semester',
            new_name='reservation',
        ),
    ]
