# Generated by Django 4.1.3 on 2022-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_rename_semester_games_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='reservation',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
    ]
