# Generated by Django 4.1.3 on 2022-12-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Games',
            new_name='games',
        ),
    ]
